ddrobot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  robot_velocity_controller:
    type: "diff_drive_controller/DiffDriveController"
    publish_rate: 50

    left_wheel: ['joint_left_front_wheel', 'joint_left_back_wheel']
    right_wheel: ['joint_right_front_wheel', 'joint_right_back_wheel']
  
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]

    wheel_radius : 0.2
    wheel_separation: 0.9
    base_frame_id: ddrobot_tf/base_footprint
    odom_frame_id: odom

    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.0   # m/s
        has_acceleration_limits: true
        max_acceleration       : 0.6   # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 2.0   # rad/s
        has_acceleration_limits: true
        max_acceleration       : 6.0   # rad/s^2


observerbot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  robot_velocity_controller:
    type: "diff_drive_controller/DiffDriveController"
    publish_rate: 50

    left_wheel: "base_to_left_wheel"
    right_wheel: "base_to_right_wheel"
  
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]

    wheel_radius : 0.2
    wheel_separation: 0.9
    base_frame_id: observerbot_tf/base_footprint
    odom_frame_id: odom

    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 0.0   # m/s
        has_acceleration_limits: true
        max_acceleration       : 0.0   # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 0.0   # rad/s
        has_acceleration_limits: true
        max_acceleration       : 0.0   # rad/s^2